export const selectedClass = 'fl-dateTimePicker-isSelect-day'
export const headerClass = 'fl-dateTimePicker-header'
export const headerYearClass = 'fl-dateTimePicker-header-year'
export const headerMonthClass = 'fl-dateTimePicker-header-month'
export const thisMonth = 'fl-dateTimePicker-this-month'
export const notThisMonth = 'fl-dateTimePicker-not-this-month'
